<?php


namespace Ablb\User;


use Ablb\Base\BaseUser;

class User_DAO extends BaseUser
{

    ////////////////////////////////////////////constructors destructor /////////////////////////////////////
    /**
     * MapRouter destructor.
     */
    public function __destruct(){
        parent::__destruct();
    }
    /**
     * MapRouter constructor.
     */
    public function __construct(){
        parent::__construct();
    }
    ///////////////////////////////////// Methods //////////////////////////////////////
    /**
     * It specify the new password for the current user. The new password cannot be null or empty.
     * @param $value string It is the new password.
     * @param $encript boolean It is true then the value will be encripted.
     */
    public function setPwd($value, $encript = true)
    {
        if( $value == null )
        {
            parent::setPwd( null );
            return;
        }
        if( strlen($value) < 1 )
        {
            parent::setPwd( null );
            return;
        }
        $pwd = $value;

        if( $encript )
        {
            $pwd = $this->getPwdControl($value);
        }
        if( $pwd == null )
        {
            return;
        }

        parent::setPwd($value); // TODO: Change the autogenerated stub
    }

}